### ISSUE TITLE
why I couldn't source bashrc in pycharm?

### ISSUE THREAD

**Issue by kaixindelele** [SurrealAI/surreal#30]
I really already installed the mujoco and successfully run test_ppo_robosuite.py in anaconda virtual env with terminal .
In other word ,I really wrote "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lyl/.mujoco/mjpro150/bin
" in ~/.bashrc
But, when I attempted to use pycharm to debug this process, I also choose suitable env , I would receive this errors:

`/home/lyl/anaconda3/envs/pytorch/bin/python /home/lyl/Downloads/surreal-master/test/test_ppo_robosuite.py
BEGIN DDPG-Gym TEST
Making temp directory...
Setting up experiment launcher...
Setting up environment variables...
replay====================done
ps====================done
eval-0====================done
Supplementary components launched
/home/lyl/.local/lib/python3.5/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Traceback (most recent call last):
  File "/home/lyl/Downloads/surreal-master/test/test_ppo_robosuite.py", line 13, in <module>
    'robosuite:SawyerLift')
  File "/home/lyl/Downloads/surreal-master/surreal/test_helpers/integration_test.py", line 77, in integration_test
    launcher.setup(args)
  File "/home/lyl/Downloads/surreal-master/surreal/main/ppo_configs.py", line 217, in setup
    self.env_config = make_env_config(self.env_config)
  File "/home/lyl/Downloads/surreal-master/surreal/env/make_env.py", line 38, in make_env_config
    env, env_config = make_env(env_config, mode)
  File "/home/lyl/Downloads/surreal-master/surreal/env/make_env.py", line 57, in make_env
    env, env_config = make_gym(env_name, env_config)
  File "/home/lyl/Downloads/surreal-master/surreal/env/make_env.py", line 69, in make_gym
    env = gym.make(env_name)
  File "/home/lyl/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/lyl/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/lyl/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/lyl/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/home/lyl/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/lyl/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/lyl/.local/lib/python3.5/site-packages/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "/home/lyl/.local/lib/python3.5/site-packages/gym/envs/mujoco/mujoco_env.py", line 11, in <module>
    import mujoco_py
  File "/home/lyl/anaconda3/envs/pytorch/lib/python3.5/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/lyl/anaconda3/envs/pytorch/lib/python3.5/site-packages/mujoco_py/builder.py", line 503, in <module>
    cymj = load_cython_ext(mjpro_path)
  File "/home/lyl/anaconda3/envs/pytorch/lib/python3.5/site-packages/mujoco_py/builder.py", line 69, in load_cython_ext
    _ensure_set_env_var("LD_LIBRARY_PATH", lib_path)
  File "/home/lyl/anaconda3/envs/pytorch/lib/python3.5/site-packages/mujoco_py/builder.py", line 118, in _ensure_set_env_var
    var_name, var_name, lib_path))
Exception: 
Missing path to your environment variable. 
Current values LD_LIBRARY_PATH=
Please add following line to .bashrc:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lyl/.mujoco/mjpro150/bin`

Anything haven't I set up correctly in pycharm?
Or how can I source ~/.bashrc when I use pycharm to debug?

**Comment by kaixindelele** [comment]
e,I found the solution in ——
[https://stackoverflow.com/questions/19715724/pycharm-environment-different-than-command-line
](url)
It seems that I raised a rookie question.
