### ISSUE TITLE
RuntimeError: Failed to initialize OpenGL when used env robosuite:SawyerLift

### ISSUE THREAD

**Issue by kaixindelele** [SurrealAI/surreal#31]
I can create surreal by using the env of gym, can successfully run :
"surreal-tmux create test --algorithm ddpg --num_agents 1 --env gym:HalfCheetah-v2"
however when I try to use the env of robosuite ,I can create process, and tensorboard is fault——
`(surreal) lyl@lyl:~/Downloads/surreal-master$ surreal-tmux l tensorboard
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_COLLECTOR_FRONTEND_PORT=7009
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_COLLECTOR_BACKEND_ADDR=127.0.0.1:7002
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PARAMETER_PUBLISH_ADDR=127.0.0.1:7007
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_COLLECTOR_FRONTEND_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PS_BACKEND_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PREFETCH_QUEUE_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PARAMETER_PUBLISH_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_TENSORBOARD_ADDR=127.0.0.1:6006
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_TENSORPLEX_PORT=7005
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_TENSORPLEX_ADDR=127.0.0.1:7005
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_TENSORBOARD_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PS_BACKEND_ADDR=127.0.0.1:7003
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PREFETCH_QUEUE_PORT=7001
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_SAMPLER_FRONTEND_PORT=7000
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PREFETCH_QUEUE_ADDR=127.0.0.1:7001
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_TENSORBOARD_PORT=6006
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_COLLECTOR_BACKEND_PORT=7002
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_SAMPLER_BACKEND_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_SAMPLER_BACKEND_ADDR=127.0.0.1:7008
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_SAMPLER_FRONTEND_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_SAMPLER_FRONTEND_ADDR=127.0.0.1:7000
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_COLLECTOR_BACKEND_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_SAMPLER_BACKEND_PORT=7008
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PS_FRONTEND_PORT=7006
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_LOGGERPLEX_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_TENSORPLEX_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_LOGGERPLEX_PORT=7004
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_LOGGERPLEX_ADDR=127.0.0.1:7004
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PS_FRONTEND_HOST=127.0.0.1
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PS_BACKEND_PORT=7003
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PS_FRONTEND_ADDR=127.0.0.1:7006
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_COLLECTOR_FRONTEND_ADDR=127.0.0.1:7009
lyl@lyl:~/Downloads/surreal-master$  export SYMPH_PARAMETER_PUBLISH_PORT=7007
lyl@lyl:~/Downloads/surreal-master$  source activate surreal
 surreal-ddpg tensorboard -- --num-agents 1 --experiment-folder /home/lyl/Downloads/surreal-master/t
ensorboardLogs/test --env robosuite:SawyerLift
(surreal) lyl@lyl:~/Downloads/surreal-master$  surreal-ddpg tensorboard -- --num-agents 1 --experime
nt-folder /home/lyl/Downloads/surreal-master/tensorboardLogs/test --env robosuite:SawyerLift
Found 1 GPUs for rendering. Using device 0.
Traceback (most recent call last):
  File "/home/lyl/anaconda3/envs/surreal/bin/surreal-ddpg", line 11, in <module>
    load_entry_point('Surreal', 'console_scripts', 'surreal-ddpg')()
  File "/home/lyl/Downloads/surreal-master/surreal/main/ddpg_configs.py", line 295, in main
    DDPGLauncher().main()
  File "/home/lyl/Downloads/surreal-master/surreal/launch/launcher.py", line 55, in main
    self.setup(config_args)
  File "/home/lyl/Downloads/surreal-master/surreal/main/ddpg_configs.py", line 273, in setup
    self.env_config = make_env_config(self.env_config)
  File "/home/lyl/Downloads/surreal-master/surreal/env/make_env.py", line 38, in make_env_config
    env, env_config = make_env(env_config, mode)
  File "/home/lyl/Downloads/surreal-master/surreal/env/make_env.py", line 59, in make_env
    env, env_config = make_robosuite(env_name, env_config)
  File "/home/lyl/Downloads/surreal-master/surreal/env/make_env.py", line 91, in make_robosuite
    reward_shaping=True,
  File "/home/lyl/anaconda3/envs/surreal/lib/python3.5/site-packages/robosuite/environments/base.py"
, line 22, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
  File "/home/lyl/anaconda3/envs/surreal/lib/python3.5/site-packages/robosuite/environments/sawyer_l
ift.py", line 135, in __init__
    camera_depth=camera_depth,
  File "/home/lyl/anaconda3/envs/surreal/lib/python3.5/site-packages/robosuite/environments/sawyer.p
y", line 91, in __init__
    camera_depth=camera_depth,
  File "/home/lyl/anaconda3/envs/surreal/lib/python3.5/site-packages/robosuite/environments/base.py"
, line 113, in __init__
    self._reset_internal()
  File "/home/lyl/anaconda3/envs/surreal/lib/python3.5/site-packages/robosuite/environments/sawyer_l
ift.py", line 192, in _reset_internal
    super()._reset_internal()
  File "/home/lyl/anaconda3/envs/surreal/lib/python3.5/site-packages/robosuite/environments/sawyer.p
y", line 110, in _reset_internal
    super()._reset_internal()
  File "/home/lyl/anaconda3/envs/surreal/lib/python3.5/site-packages/robosuite/environments/base.py"
, line 172, in _reset_internal
    render_context = MjRenderContextOffscreen(self.sim)
  File "mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mjrendercontext.pyx", line 108, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "opengl_context.pyx", line 128, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL
(surreal) lyl@lyl:~/Downloads/surreal-master$
`
I've seen the previous issues, but I haven't found a solution?

**Comment by LinxiFan** [comment]
Can you try again with `surreal-subproc`? Tmux is deprecated now. 
Also please make sure your virtualenv has the required dependencies installed.
